### PR TITLE
M0 bugs

### LINKED ISSUE #699: rtime-m0-test and master streams not matching

### PR DESCRIPTION
**Pull request by hguermaz**
## Description

Address streams mismatch between rtime-m0-test and master:
- ALTREF : fixed actual_future_pics derivation, shut padding of the central frame, fixed end past frame index prior @ window shrinking.
- NEAREST_NEW: fixed injection and fixed settings.
- ESTIMATE_INTRA : fixed settings.
- SKIP_REDUNDANT_BLOCK: fixed the action to bypass MD.
- COEF_BASED_ATB_SKIP : reset coeff_based_skip_atb @ each SB.
- WM_SETTINGS: fixed settings.
- ENABLE_CDF_UPDATE: removed useless update.
- SORTING @ md_stage_1: used same sorting method.
- SEGMENT_RESET: only @ 1st segment.
- COMPOUND: used block size @ the derivation of compound count.

Closes #699 

## Author

@hassount 
@hguermaz 

## Type of change

Bug fixes.

## Tests and performance
* BD-Rate to aom cpu0-2pass on 360p/720p: ~0.5% gain.
* Speed on a 4-core machine for M0 on 360p: ~0%.
* Memory footprint on a 4-core machine: negligible.

### CODE REVIEW

File: Source/Lib/Common/Codec/EbProductCodingLoop.c [hunk 1]
```diff
@@ -7711,77 +7735,82 @@ EB_EXTERN EbErrorType mode_decision_sb(
...
+                if (parent_depth_cost <= current_depth_cost + (current_depth_cost* (4 - context_ptr->blk_geom->quadi)* MD_EXIT_THSL / context_ptr->blk_geom->quadi / 100)) {
 #endif
-                skip_next_sq = 1;
-                next_non_skip_blk_idx_mds = parent_depth_idx_mds + ns_depth_offset[sequence_control_set_ptr->seq_header.sb_size == BLOCK_128X128][context_ptr->blk_geom->depth - 1];
+                    skip_next_sq = 1;
+                    next_non_skip_blk_idx_mds = parent_depth_idx_mds + ns_depth_offset[sequence_control_set_ptr->seq_header.sb_size == BLOCK_128X128][context_ptr->blk_geom->depth - 1];
+                }
+                else {
+                    skip_next_sq = 0;
+                }
```
Comment (joelsole) [inline Source/Lib/Common/Codec/EbProductCodingLoop.c]: no braces

Comment (hassount) [reply Source/Lib/Common/Codec/EbProductCodingLoop.c]: Done, thnx
