### PR TITLE
size of n_alloc_len changes based on bitstream count

### LINKED ISSUE #1136: encoding error causing by extra large encode size under small qp
encoding error for certain yuv using small qp, this issue can be reproduced 100% with certain yuv file.
my command line and error log is like following.
image

### LINKED ISSUE #1174: Crash in 4k Resolution
## Preset
 8
## Occurrence
 Reproducible
##  Sequence used
Netflix_ToddlerFountain_4096x2160_60fps_10bit_420_60f
Campfire_3840x2160_30fps_10bit_bt709_420_videoRange_60f
ParkRunning3_3840x2160_50fps_10bit_420_60f
## Command line Sample
SvtAv1EncApp -enc-mode 8 -w 3840 -h 2160 -bit-depth 10 -fps-num 30000 -fps-denom 1000 -q 20  -n  60.0  -intra-period  63 -lad 0 -lp 1  -i  Campfire_3840x2160_30fps_10bit_bt709_420_videoRange_60f.yuv  -b  Campfire_3840x2160_30fps_10bit_bt709_420_videoRange_60f_Q20.bin
## Description
* Used master @ b5cdb0b revision-hash 
* Error Message: `Svt[error]: encode size(5013174) is too largeSvt[error]: bug, no frame in undisplayed queue`
* ran 5 QPs [20,32,43,55,63] and the problem only showed up in QP20
* Error is output in the first few frames 
* Encoding stops around frames 45-48

### PR DESCRIPTION
**Pull request by mazharaIntel**
# Description

`n_alloc_len` is now set dynamically rather than the hardcoded values.
Resolves issues when encoding a high-resolution input with a low QP value by dynamically reallocating the buffer.

@xuguangxin, @EricLamVCD 

# Issue

Resolves #1136
Resolves #1174

# Author
@mazharaIntel 
@1480c1

# Performance impact

- [ ] quality
- [x] memory
- [ ] speed
- [x] 8 bit
- [x] 10 bit
- [ ] N/A

# Test set

- [ ] obj-1-fast
- [ ] other
- [ ] N/A
- [x] Has not been tested yet

# Squash and merge (Allow maintainer to squash and merge when PR is ready)
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by hassount** [comment]
@mazharaIntel thank you for the PR, can you please update the description to both give a better description of the problem, link to the issues that are applicable and follow a similar format as #1149 for example

**Comment by hassount** [comment]
@mazharaIntel, thank you for the updated description. your patch includes some formatting changes, can you please remove all of the formatting changes and keep only the changes that are needed ?

**Comment by 1480c1** [comment]
@mazharaIntel please use something like either `git commit --amend` or `git rebase -i` and reword your commit, `initial commit` is not very descriptive

**Comment by 1480c1** [comment]
Also if this pr fixes the issues you mentioned, please use the `fixes #1136` or `closes #1136` format inside the main body of the original post. It will help with menial task such as auto-closing the related issues once this is merged

https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c [hunk 1]
```diff
@@ -857,7 +863,7 @@ void *packetization_kernel(void *input_ptr) {
         // Process the head of the queue
         //****************************************************
         // Look at head of queue and see if we got a td
-        int total_bytes;
```
Comment (hassount) [inline Source/Lib/Encoder/Codec/EbPacketizationProcess.c:860]: still don't understand why we moved this ? up to line 781 it is set to 0

Comment (mazharaIntel) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:860]: For one of the run, the first value for total_bytes till line 781 is -855993460 (which I assume is garbage value).  The second value is 0 and the third value is 1249621(valid value) and so on. So I put total_bytes up and initialized to 0.

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:860]: total_bytes is passed in by reference to the next function, so it not being initialized at the beginning makes sense.

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c [hunk 2]
```diff
@@ -751,6 +752,11 @@ void *packetization_kernel(void *input_ptr) {
 
         write_frame_header_av1(pcs_ptr->bitstream_ptr, scs_ptr, pcs_ptr, 0);
 
+        output_stream_ptr->n_alloc_len = bitstream_get_bytes_count(pcs_ptr->bitstream_ptr) + TD_SIZE;
+        output_stream_ptr->p_buffer    = (uint8_t *)malloc(output_stream_ptr->n_alloc_len);
+
```
Comment (tianjunwork) [inline Source/Lib/Encoder/Codec/EbPacketizationProcess.c:757]: @hassount, Just curious, only the last OBU is post to app, and release from there. How rest OBUs p_buffer is freed?

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c [hunk 3]
```diff
@@ -548,7 +552,7 @@ static void encode_tu(EncodeContext *encode_context_ptr, int frames, int total_b
         memmove(dst, src_stream_ptr->p_buffer, size);
```
[the remark this answers is not in the document]
Comment (1480c1) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:552]: I'm not sure, @xuguangxin might have more information about this, but assuming there is no possible overlap between the two data arrays, it would be better to use memcpy

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c (hunk 2 above)
Comment (xuguangxin) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:757]: It will free by svt_av1_enc_release_out_buffer. It's not necessary, we can free it only at deinit time.

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c [hunk 4]
```diff
@@ -529,17 +529,21 @@ static void collect_frames_info(PacketizationContext* context_ptr, const EncodeC
...
 //a tu start with a td, + 0 more not displable frame, + 1 display frame
-static void encode_tu(EncodeContext *encode_context_ptr, int frames, int total_bytes,
+static void encode_tu(EncodeContext *encode_context_ptr, int frames, size_t total_bytes,
                       EbBufferHeaderType *output_stream_ptr) {
     total_bytes += TD_SIZE;
-    if (total_bytes > (int)output_stream_ptr->n_alloc_len) {
-        SVT_ERROR("encode size(%d) is too large", total_bytes);
-        return;
+    if (total_bytes > output_stream_ptr->n_alloc_len) {
+        uint8_t *pbuff = (uint8_t *)realloc(output_stream_ptr->p_buffer, total_bytes);
```
[the remark this answers is not in the document]
Comment (1480c1) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c]: Switched

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c (hunk 2 above)
Comment (xuguangxin) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: yes, you are right, we may have a leak, we can consider use EB_MALLOC TO tracking the memory.

free buffer in svt_av1_enc_release_out_buffer is not necessary, maybe we can keep the memory and reuse it in the packetization process.

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c [hunk 5]
```diff
@@ -751,6 +752,11 @@ void *packetization_kernel(void *input_ptr) {
 
         write_frame_header_av1(pcs_ptr->bitstream_ptr, scs_ptr, pcs_ptr, 0);
 
+        output_stream_ptr->n_alloc_len = bitstream_get_bytes_count(pcs_ptr->bitstream_ptr) + TD_SIZE;
```
[the remark this answers is not in the document]
Comment (1480c1) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:768]: Based on limited testing, yes, since without it, encoding will hang and will be stuck in a mutex lock or something, have not investigated any further than that.

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c (hunk 2 above)
Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:770]: it's best to not use EB_MALLOC in this case otherwise the memory will start creeping up too much, these are very small buffers so allocating them at run time is not a big deal in my opinion

Comment (1480c1) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:770]: Okay, I will switch it back to using basic malloc

Comment (xuguangxin) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Hi @hassount , EB_MALLOC has zero overhead at release time. and it will track the memory leak at debug time.  The benefit is it will tracking all memory leaks.

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Agreed that there's not much overhead, however, the call for EB_MALLOC would basically ask for more memory for every packet and free it all at the end which makes the resident memory on the system higher than using malloc / free thus the overhead I am referring to.

Comment (xuguangxin) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Hi @hassount , it will not ask more memory at release build. For release build,  it equals malloc. No extra memory tracking structure need.

It will not ask more memory debug build too. The memory tracking hast bucket already been allocated. 

see https://github.com/OpenVisualCloud/SVT-AV1/blob/1851716d7b1e1476eca7b5a1d09a5c4c848a74d7/Source/Lib/Common/Codec/EbMalloc.h#L13-L15

thanks

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: @xuguangxin it seems that we’re not on the same page. I am not referring to the fact that the malloc’d memory will be different, this is about being the active amount of memory. Imagine using EB_MALLOC and encoding 1M frames, each frame will be allocating an output buffer and they will be all be freed at deinit time. So as long as the encoding is going on, we’ll be asking for more memory which will add up to gigs of memory. Whereas in this case, the output buffers life time is much smaller as they don’t need to remain in the RAM for too long

Comment (tianjunwork) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Hi @hassount , after Guangxin refactor resources allocation, there is no global list to hold all mem entries. EB_MALLOC is essentially same as malloc now.

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: @tianjunwork thank you for the explanation, it seems that I misunderstood the new EB_MALLOC work flow. In this case, it would be best to use EB_MALLOC everywhere to be able to make sure that all pointers have been freed ?

**Comment by 1480c1** [comment]
Accidentally submitted cppcheck stuff here

File: Source/Lib/Encoder/Codec/EbPacketizationProcess.c (hunk 2 above)
Comment (1480c1) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Do we want to change all of the `malloc` calls in the library to `EB_MALLOC` in a separate PR?

Other than the malloc functions, there are currently 18 calls to malloc in `Source/Lib/Common/*` and other than the two currently in this PR, there are 60 calls to malloc in `Source/Lib/Encoder/*`

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Yes let’s do that in a separate PR

Comment (xuguangxin) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: yes, Jun is right, thanks for explaining this. Now I see why the previous code did not use EB_MALLOC now.

Comment (tianjunwork) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:762]: Note that buffer posted to app can't use EB_FREE which is only for the library. So in debug build, a list is used to track mem allocation. Using EB_MALLOC and free in pair will show mem leak since the pointer is not removed from the list.

Comment (1480c1) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:770]: Switched to `EB_MALLOC` again

Comment (tianjunwork) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:770]: For above reason, buffer allocation in PK should just use malloc.

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:770]: Now I am confused again, can we not use EB_MALLOC and EB_FREE when the app calls back? @1480c1 let’s merge this with malloc and free a s we’ll do another PR with generalizing EB_MALLOC

Comment (hassount) [reply Source/Lib/Encoder/Codec/EbPacketizationProcess.c:770]: Now I am confused again, can we not use EB_MALLOC and EB_FREE when the app calls back? @1480c1 let’s merge this with malloc and free a s we’ll do another PR with generalizing EB_MALLOC

**Comment by 1480c1** [comment]
@hassount pr is ready to merge

**Comment by hassount** [comment]
> @hassount pr is ready to merge

thank you @1480c1 pinging @andrey-norkin
