### PR TITLE
Bug fixes

### LINKED ISSUE #473: [SVT AV1]The output stream playback screen is green screen with setting "-tile-rows" and "-tile-columns" to encode in encMode[0] for 1920x1080 and 1280x720 resolution.
[Test environment]
 OS： Ubuntu 18.04.2 LTS
 SVT CommitID: d2e95a3
 
[Issue Description]
When we use SvtAv1EncApp to do encoding with setting "-tile-rows" and "-tile-columns" in encMode[0] for 1920x1080 and 1280x720 resolution, we found that the output streams playback failed, the playback screen is a green screen.

This issue does not occur in below situations:
1. encMode[1-8] for 1920x1080 and 1280x720 resolution
2. encMode[0-8] for 4096x2160 and 720x480 resolution

The command line we used is:
SvtAv1EncApp -i Fallout4_1920x1080_8bit_60Hz_P420.yuv  -b tile_test_M0_Fallout4_1920x1080_8bit_60Hz_P420_Q45_0_1.bin  -w 1920  -h 1080  -bit-depth 8  -fps 60  -intra-period 55  -n 20  -enc-mode 0  -compressed-ten-bit-format 0  -q 45  -tile-columns 1  -rc 0  -tile-rows 0

SvtAv1EncApp -i DucksTakeOff_1280x720_8bit_50Hz_P420.yuv  -b tile_test_M0_DucksTakeOff_1280x720_8bit_50Hz_P420_RC3_1126173bps_4_6.bin  -w 1280  -h 720  -bit-depth 8  -fps 50  -intra-period 47  -n 20  -enc-mode 0  -tbr 1126173  -compressed-ten-bit-format 0  -tile-columns 6  -rc 3  -tile-rows 4

### PR DESCRIPTION
**Pull request by ttrigui**
+ Fix R2R CFL  : store luma data for 4xN and Nx4 blocks regardless of the candidate type and chrome mode 
+ Add a check on parent CU availability before checking the merge algorithm
+ Fix TILE ATB 
+ Fix R2R for split rate
Fixes #473

### CODE REVIEW

File: Source/Lib/Common/Codec/EbFullLoop.c [hunk 1]
```diff
@@ -3069,53 +3070,57 @@ void   compute_depth_costs(
...
-                context_ptr,
-                &context_ptr->md_cu_arr_nsq[curr_depth_blk3_mds],
-                0,
-                PARTITION_NONE,
-                &curr_non_split_rate_blk3,
-                context_ptr->full_lambda,
-                context_ptr->md_rate_estimation_ptr,
-                sequence_control_set_ptr->max_sb_depth);
+        if (context_ptr->md_local_cu_unit[curr_depth_blk0_mds].tested_cu_flag)
+            if (context_ptr->md_cu_arr_nsq[curr_depth_blk0_mds].mdc_split_flag == 0)
```
Comment (joelsole) [inline Source/Lib/Common/Codec/EbFullLoop.c]: Could these additional conditions on tested_cu_flag be in the existing if statement? This would add clarity to the intention of the change.

Comment (chkngit) [reply Source/Lib/Common/Codec/EbFullLoop.c]: it is a matter of Valgrind that will  complain if it hits a non initilized value (mdc_split_flag)

**Comment by hassount** [comment]
@joelsole @chkngit 
Have all items been resolved ?
